"""Initial migration

Revision ID: 69099db00b48
Revises: 
Create Date: 2025-07-15 17:27:50.546639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69099db00b48'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobcards', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jobcards', 'users', ['user_id'], ['id'])
    op.add_column('serviceorders', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'serviceorders', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'serviceorders', type_='foreignkey')
    op.drop_column('serviceorders', 'user_id')
    op.drop_constraint(None, 'jobcards', type_='foreignkey')
    op.drop_column('jobcards', 'user_id')
    # ### end Alembic commands ###
